# Temperature Prediction

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
dataset = pd.read_csv('../Datasets/SzegedWeatherHistory.csv')

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  int64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  int64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 8.8+ MB

In [14]:
dataset.head(10)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258,14.9569,0,1016.66,Partly cloudy throughout the day.
6,2006-04-01 06:00:00.000 +0200,Partly Cloudy,rain,7.733333,5.522222,0.95,12.3648,259,9.9820,0,1016.72,Partly cloudy throughout the day.
7,2006-04-01 07:00:00.000 +0200,Partly Cloudy,rain,8.772222,6.527778,0.89,14.1519,260,9.9820,0,1016.84,Partly cloudy throughout the day.
8,2006-04-01 08:00:00.000 +0200,Partly Cloudy,rain,10.822222,10.822222,0.82,11.3183,259,9.9820,0,1017.37,Partly cloudy throughout the day.
9,2006-04-01 09:00:00.000 +0200,Partly Cloudy,rain,13.772222,13.772222,0.72,12.5258,279,9.9820,0,1017.22,Partly cloudy throughout the day.

In [15]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [18]:
X

array([['2006-04-01 00:00:00.000 +0200', 'Partly Cloudy', 'rain', ...,
        15.8263, 0, 1015.13],
       ['2006-04-01 01:00:00.000 +0200', 'Partly Cloudy', 'rain', ...,
        15.8263, 0, 1015.63],
       ['2006-04-01 02:00:00.000 +0200', 'Mostly Cloudy', 'rain', ...,
        14.9569, 0, 1015.94],
       ...,
       ['2016-09-09 21:00:00.000 +0200', 'Partly Cloudy', 'rain', ...,
        16.1, 0, 1015.66],
       ['2016-09-09 22:00:00.000 +0200', 'Partly Cloudy', 'rain', ...,
        16.1, 0, 1015.95],
       ['2016-09-09 23:00:00.000 +0200', 'Partly Cloudy', 'rain', ...,
        15.5204, 0, 1016.16]], dtype=object)

array(['Partly cloudy throughout the day.',
       'Partly cloudy throughout the day.',
       'Partly cloudy throughout the day.', ...,
       'Partly cloudy starting in the morning.',
       'Partly cloudy starting in the morning.',
       'Partly cloudy starting in the morning.'], dtype=object)